### ISSUE TITLE
Optional SSL also for ES startup check script

### ISSUE THREAD

**Issue by michaloo** [khezen/docker-elasticsearch#13]
Hey,

I didn't have much time to test it, but it looks like the `HTTP_SSL` is not covered at this line:

https://github.com/Khezen/docker-elasticsearch/blob/master/src/miscellaneous/wait_until_started.sh#L5

If I turn off the SSL on port 9200 that script will try to use SSL anyway which will fail.

**Comment by khezen** [comment]
true I'll fix it quickly. Thanks for reporting.
