### ISSUE TITLE
elastalert_1 ... ImportError: No module named botocore.session

### ISSUE THREAD

**Issue by cumpelik** [khezen/docker-elasticsearch#14]
Hi,
first: thanks to the author for great work for all of us. 
However :) - we tried to follow your instruction on debian to run the ELK. Kibama seems to be working fine, however I'm not able to connect to elastic. Neither from kibana nor code. From kibana it says "no permissions for indices:data/read/search". 
We found some alerts in logs. Can it cause the problem? (we left all credentials in default)

elastalert_1     |                                  Dload  Upload   Total   Spent    Left  Speed
100   340  100   340    0     0   6210      0 --:--:-- --:--:-- --:--:--  6296
elastalert_1     | { "name" : "ab199d2af982", "cluster_name" : "elasticsearch-default", "cluster_uuid" : "Wn5FGOtUS6ObiU5aoQM3iQ", "version" : { "number" : "5.4.0", "build_hash" : "780f8c4", "build_date" : "2017-04-28T17:43:27.229Z", "build_snapshot" : false, "lucene_version" : "6.5.0" }, "tagline" : "You Know, for Search" }
elastalert_1     | Traceback (most recent call last):
elastalert_1     |   File "/usr/local/bin/elastalert-create-index", line 6, in <module>
elastalert_1     |     from pkg_resources import load_entry_point
elastalert_1     |   File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 3019, in <module>
elastalert_1     |   File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 3003, in _call_aside
elastalert_1     |   File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
elastalert_1     |   File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 657, in _build_master
elastalert_1     |   File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 670, in _build_from_requirements
elastalert_1     |   File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 854, in resolve
elastalert_1     | pkg_resources.ContextualVersionConflict: (requests 2.4.3 (/usr/lib/python2.7/dist-packages), Requirement.parse('requests>=2.10.0'), set(['jira']))
elastalert_1     | $@
elastalert_1     | Traceback (most recent call last):
elastalert_1     |   File "/elastalert/elastalert/elastalert.py", line 18, in <module>
elastalert_1     |     import kibana
elastalert_1     |   File "/elastalert/elastalert/kibana.py", line 4, in <module>
elastalert_1     |     from util import EAException
elastalert_1     |   File "/elastalert/elastalert/util.py", line 8, in <module>
elastalert_1     |     from auth import Auth
elastalert_1     |   File "/elastalert/elastalert/auth.py", line 3, in <module>
elastalert_1     |     import boto3
elastalert_1     |   File "/usr/local/lib/python2.7/dist-packages/boto3-1.4.4-py2.7.egg/boto3/__init__.py", line 16, in <module>
elastalert_1     |     from boto3.session import Session
elastalert_1     |   File "/usr/local/lib/python2.7/dist-packages/boto3-1.4.4-py2.7.egg/boto3/session.py", line 17, in <module>
elastalert_1     |     import botocore.session
elastalert_1     | ImportError: No module named botocore.session

 340    0     0   6503      0 --:--:-- --:--:-- --:--:--  6538
elastalert_1     | { "name" : "ab199d2af982", "cluster_name" : "elasticsearch-default", "cluster_uuid" : "Wn5FGOtUS6ObiU5aoQM3iQ", "version" : { "number" : "5.4.0", "build_hash" : "780f8c4", "build_date" : "2017-04-28T17:43:27.229Z", "build_snapshot" : false, "lucene_version" : "6.5.0" }, "tagline" : "You Know, for Search" }
kibana_1         | {"type":"response","@timestamp":"2017-05-16T07:21:16Z","tags":[],"pid":34,"method":"get","statusCode":302,"req":{"url":"/","method":"get","headers":{"host":"localhost:5601","user-agent":"Links (2.8; Linux 3.16.0-4-amd64 x86_64; GNU C 4.9.1; text)","accept":"*/*","accept-language":"en,*;q=0.1","accept-encoding":"gzip,deflate,bzip2,lzma,lzma2","accept-charset":"us-ascii,ISO-8859-1,ISO-8859-2,ISO-8859-3,ISO-8859-4,ISO-8859-5,ISO-8859-6,ISO-8859-7,ISO-8859-8,ISO-8859-9,ISO-8859-10,ISO-8859-13,ISO-8859-14,ISO-8859-15,ISO-8859-16,windows-1250,windows-1251,windows-1252,windows-1256,windows-1257,cp437,cp737,cp850,cp852,cp866,x-cp866-u,x-mac,x-mac-ce,x-kam-cs,koi8-r,koi8-u,koi8-ru,TCVN-5712,VISCII,utf-8","connection":"keep-alive"},"remoteAddress":"172.18.0.1","userAgent":"172.18.0.1"},"res":{"statusCode":302,"responseTime":2,"contentLength":9},"message":"GET / 302 2ms - 9.0B"}
kibana_1         | {"type":"response","@timestamp":"2017-05-16T07:21:16Z","tags":[],"pid":34,"method":"get","statusCode":200,"req":{"url":"/searchguard/login?nextUrl=%2F","method":"get","headers":{"host":"localhost:5601","user-agent":"Links (2.8; Linux 3.16.0-4-amd64 x86_64; GNU C 4.9.1; text)","accept":"*/*","accept-language":"en,*;q=0.1","accept-encoding":"gzip,deflate,bzip2,lzma,lzma2","accept-charset":"us-ascii,ISO-8859-1,ISO-8859-2,ISO-8859-3,ISO-8859-4,ISO-8859-5,ISO-8859-6,ISO-8859-7,ISO-8859-8,ISO-8859-9,ISO-8859-10,ISO-8859-13,ISO-8859-14,ISO-8859-15,ISO-8859-16,windows-1250,windows-1251,windows-1252,windows-1256,windows-1257,cp437,cp737,cp850,cp852,cp866,x-cp866-u,x-mac,x-mac-ce,x-kam-cs,koi8-r,koi8-u,koi8-ru,TCVN-5712,VISCII,utf-8","connection":"keep-alive"},"remoteAddress":"172.18.0.1","userAgent":"172.18.0.1"},"res":{"statusCode":200,"responseTime":7,"contentLength":9},"message":"GET /searchguard/login?nextUrl=%2F 200 7ms - 9.0B"}

Thank you for any hints. I'm quite new in linux/docker/elk.
M.C.

**Comment by khezen** [comment]
I have no issue with kibana and elasticsearch auth on my side. 

Elastalert is built from yelp/elastalert:master. I will implement tags bound on stable releases instead. I'd advise you to raise an issue to Yelp/elastalert if the issue persist.

If you have issues with the whole stack, please raise an issue to [khezen/compose-elk](https://github.com/Khezen/compose-elk/issues)
