### ISSUE TITLE
failed to find manifest for elasticsearch:5.4.1

### ISSUE THREAD

**Issue by atomicom** [khezen/docker-elasticsearch#17]
Hi,

When I run docker-compose up from the Test folder. It complains that there is no manifest for elasticsearch:5.4.1

[root@container01 test]# docker-compose up
Building elasticsearch
Step 1/15 : FROM elasticsearch:5.4.1
ERROR: Service 'elasticsearch' failed to build: manifest for elasticsearch:5.4.1 not found

If I edit the Docker file to build from docker.elastic.co/elasticsearch/elasticsearch:5.4.1 instead I get a bunch of other errors with regards to permissions.

**Comment by khezen** [comment]
Yes this image is no longer maintained. I need to migrate to a new solution.

**Comment by khezen** [comment]
solved.
