### ISSUE TITLE
Adding management REST API

### ISSUE THREAD

**Issue by lshahar** [khezen/docker-elasticsearch#18]
Hi,
There is plan to add the management api ? 
https://github.com/floragunncom/search-guard-rest-api
https://github.com/floragunncom/search-guard-docs/blob/master/managementapi.md

**Comment by khezen** [comment]
That would be nice indeed. I'll see what I can do ;)

**Comment by Khezen** [comment]
Hi, unfortunately search-guard-rest-api does not support [versions](https://github.com/floragunncom/search-guard-rest-api/releases) higher than 5.3.5

I've created an [issue for 5.4.2 support](https://github.com/floragunncom/search-guard-rest-api/issues/8).
https://github.com/floragunncom/search-guard-rest-api/issues/8

**Comment by floragunn** [comment]
Pls keep in mind that you need to obtain a commercial license if you run the rest management api in production!

**Comment by khezen** [comment]
will create a new tag.

**Comment by pgbezerra** [comment]
IMHO this shouldn't be opened by default.  
I guess that we have to enable this with a environment variable and disabled by default.

@floragunncom already warn about this.

**Comment by pgbezerra** [comment]
@johnkchiu

**Comment by khezen** [comment]
Is the whole product disabled in case of a commercial feature being used without licence or just these features are disabled and community features remain enabled? @floragunncom

**Comment by floragunn** [comment]
You can have a look here: https://search-guard.com/faq/
Why not ship the container with `searchguard.enterprise_modules_enabled: false` by default and anyone who like to evaluate the commercial feature (has obtained a license) can turn it on. It's possible to use env vars also in elasticsearch.yml to control this property.

**Comment by khezen** [comment]
https://github.com/khezen/docker-elasticsearch/commit/e3ce404a17b21ceca0fd5bcd30a1a209f30ec23b
