### ISSUE TITLE
Shoud use environment in "index_level_settings.sh" and "wait_until_started.sh"?

### ISSUE THREAD

**Issue by zj8487** [khezen/docker-elasticsearch#22]
Hi khezen, 
I notice [wait_until_started.sh](https://github.com/khezen/docker-elasticsearch/blob/master/src/miscellaneous/wait_until_started.sh#L10) and [index_level_settings.sh](https://github.com/khezen/docker-elasticsearch/blob/master/src/miscellaneous/index_level_settings.sh#L8) can only work on the ```http://localhost:9200```. shoud we use environment for the ```http or https```, ```localhost```, ```9200``` ?

**Comment by khezen** [comment]
Good point but if you look closer you'll see it uses a variable set to the correct protocol.
```
http="http"
if [ $HTTP_SSL ]; then
  http="https"
fi
while [[ RET -ne 0 ]]; do
    echo "Stalling for Elasticsearch..."
    curl -XGET -k -u "elastic:$$ELASTIC_PWD" "$http://localhost:9200/" >/dev/null 2>&1
    RET=$?
    sleep 5
done
```
