### ISSUE TITLE
wait_until_started.sh run forever if es is not configured

### ISSUE THREAD

**Issue by tdi** [khezen/docker-elasticsearch#23]
This script runs forever if es is not configured, I believe it should have a limit of trials, after which the whole container should fail. This needs also some changes in the entrypoint.sh.

**Comment by khezen** [comment]
What do you mean by not configured? could you provide an example?

**Comment by tdi** [comment]
When you misconfigure your es and it does not start for some reason, your wait for script  will poll indefinitely. Hence the container will be running indefinitely.

**Comment by khezen** [comment]
I am kept busy by other projects and I won't implement it soon. Do you want to try a pull request?

If not, you can still use the health check endpoint from elasticsearch API [GET _cluster/health](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-health.html) in your container orchestration.
