### ISSUE TITLE
command ``gosu`` not found when using elasticsearch 6.0

### ISSUE THREAD

**Issue by swdream** [khezen/docker-elasticsearch#25]
Hello,
I upgraded elasticsearch from version 5.5.0 to 6.0 using docker image https://hub.docker.com/r/khezen/elasticsearch/tags/ and I get this error in the log:
```
/run/entrypoint.sh: line 16: gosu: command not found
/run/entrypoint.sh: line 17: gosu: command not found
/run/entrypoint.sh: line 22: gosu: command not found
Stalling for Elasticsearch...
```
``gosu`` command is used 
https://github.com/khezen/docker-elasticsearch/blob/master/src/entrypoint.sh#L16
but seems that it has not installed yet. Please help me to confirm.
thanks a lot

**Comment by quantonganh** [comment]
Because of this: https://github.com/khezen/docker-elasticsearch/commit/6198ea5178c339e4f623695329f40391063accc7#diff-3254677a7917c6c01f55212f86c57fbf

**Comment by khezen** [comment]
thanks for helping!
