### ISSUE TITLE
Getting stuck on creating an index pattern on 6.1.1

### ISSUE THREAD

**Issue by brunofvalli** [khezen/docker-elasticsearch#36]
So installed 6.1.1 fine with ElasticSearch and Kibana, but when I tried to create a Index Pattern it just sits there and does nothing. I reverted back to version 6.0.0 and there it works fine.

Looking around I found this issue in the searchguard git hub:

https://github.com/floragunncom/search-guard/issues/444

and they said the following about the issue:

This is not an error in Search Guard. We used the the original repos you mentioned above and after configuring multi tenancy everything works as expected.

However, the Dockerfiles and the especially the SG configuration in this repo is not correct:

Multi tenancy is not enabled in sg_config
The Kibana server user that is configured in kibana.yml is not configured in sg_config
There is only one Kibana role, usually you should use two, one for the Kibana serve user, one for regular Kibana users
The permissions for the Kibana server user are not correct. They especially lack the indices:admin/template* permission
the "sgtenant" HTTP header is not whitelisted in kibana.yml
After fixing all these configuration errors in the Dockerfile everything works as expected. If you need further assistance in settup up MT, please ask on the Google Groups: https://groups.google.com/forum/#!forum/search-guard

Not sure if this is something you are aware of.

**Comment by khezen** [comment]
```
Multi tenancy is not enabled in sg_config
```
It is up to you to enable it. Keep in mind that it is not included in Search Guard community edition and you'll need to buy a Licence from *floragunncom* to run this feature on production.

```
The Kibana server user that is configured in kibana.yml is not configured in sg_config
```
It is.

```
There is only one Kibana role, usually you should use two, one for the Kibana serve user, one for regular Kibana users

The permissions for the Kibana server user are not correct. They especially lack the indices:admin/template* permission
```
This image comes with default config. Then it is up to you to define your own policy. You can edit the configuration files, restart your services and run sgadmin. Although, I would advice against using kibana to create index templates unless you are going to populate it through Kibana as well which would be weired but you may have a use case for it. 
:+1: I agree it is a good practice to split kibana server and user permissions and I may change the default config to comply to it.

```
the "sgtenant" HTTP header is not whitelisted in kibana.yml
```
:+1:  I will add it in the default config

**Comment by khezen** [comment]
- [x] [whitelisting header Authorization sgtenant](https://github.com/khezen/docker-kibana/commit/fae96bcaba429a730be7342c4560899920ec0514)
