### ISSUE TITLE
Incorrect 'host' in sg_roles_mapping.yml.

### ISSUE THREAD

**Issue by jala-dx** [khezen/docker-elasticsearch#38]
It has to be 'hosts' not 'host'. if we do not have this correctly, you may land up deleting other indices of other users.

https://github.com/khezen/docker-elasticsearch/blob/master/config/searchguard/sg_roles_mapping.yml#L12

Please see Search guard code..
https://github.com/floragunncom/search-guard/blob/master/src/main/java/com/floragunn/searchguard/configuration/PrivilegesEvaluator.java#L1068

Thanks.
Jalaja

**Comment by khezen** [comment]
Thank you for reporting Jalaja.

**Comment by khezen** [comment]
https://github.com/khezen/docker-elasticsearch/commit/773317c0a07da5030f9ef419dabfa3494dcd743b
