### ISSUE TITLE
Deprecation oft this project should be removed

### ISSUE THREAD

**Issue by xtermi2** [khezen/docker-elasticsearch#39]
You have to read the Elastic web page carefully, X-Pack is NOT under Apache 2.0 license, it's Elastic license! This means only some (More or less basic monitoring) features of X-Pack is in free tire: https://www.elastic.co/subscriptions
Security and auth is NOT in free tire! So this image will stay important for users who want to use Search guard with ES 6.3!

**Comment by khezen** [comment]
thank you @xtermi2
