### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by xermus** [khezen/docker-elasticsearch#43]
No matter what I do, I get:

**standard_init_linux.go:190: exec user process caused "no such file or directory"**

I am running Docker on Windows 10

```bash
docker run -p 9200:9200 -p 9300:9300 -e ELASTIC_PWD=changeme -e KIBANA_PWD=changeme  khezen/elasticsearch:latest
```

in an Active Directory environment with shared drives enabled. I cloned the official Git repo. I loaded Docker as administrator and Powershell as administrator.

Why is this not working and how can this be fixed?

**Comment by khezen** [comment]
Hi Xermus I am not sure this image is compatible with Widows Server. You might want to write your own Dockerfile if you want to follow that path.

**Comment by khezen** [comment]
no reply > 7 days -> close
