### ISSUE TITLE
Question on data volumes for elasticsearch in openshift

### ISSUE THREAD

**Issue by anandgavai** [khezen/docker-elasticsearch#48]
We just aquired enterprise liscence for Search Guard. I have got few questions below for you consideration.

1. I have a persistent volume on my openshift cluster (I can share yaml file for this) /usr/share/elasticsearch/data. I am running elasticsearch version 6.1.4. If I use the docker image (based on 6.1.4 and 22.3 SG version) from this repo with SG enterprise features enabled and point volume (/elasticsearch/data) to same persistant storage would this work ?

2. if the above will work based on a new version of elasticsearch and SG enterprise ?

**Comment by khezen** [comment]
Hi anandgavai, I have no experience running openshift on a production environment so I assume  you know better than me on that topic.

**Comment by anandgavai** [comment]
Alright thanks !
